default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "reco_development" } %>
  host: <%= ENV.fetch("DB_HOST") { "postgres_reco" } %>
  port: <%= ENV.fetch("DB_PORT") { "5432" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "postgres" } %>

test:
  <<: *default
  database: reco_test
  host: postgres_reco
  port: 5432
  username: postgres
  password: postgres

production:
  <<: *default
  database: reco_production
  username: reco
  password: <%= ENV["RECO_DATABASE_PASSWORD"] %>
